- name: Instalar e iniciar o NGINX
  hosts: nginx
  become: true

  tasks:
   - name: Atualizar a cache de pacotes do APT
     ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 3600

   - name: Instalar o Nginx
     ansible.builtin.apt:
      name: nginx
      state: present

   - name: Iniciar o serviço
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: true
